name: main
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  core:
    git:
      url: https://github.com/phferreira/core.git
      ref: master

  login:
    git:
      url: https://github.com/phferreira/login.git
      ref: master

  home:
    git:
      url: https://github.com/phferreira/home.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true